#!/bin/bash

if type -P figlet >/dev/null ; then
  fonts=( bell block cricket cyberlarge cybermedium lean ogre shadow slant stampatello standard starwars )
  let "idx = ${RANDOM} % ${#fonts[@]}"
  font="${fonts[${idx}]}"
  echo -e "$(tput setaf 136)$(figlet -f ${font}  -c -w $( tput cols ) $( hostname -s ) )"
  exit
fi

cat <<'EOF'
[1;37m#[38;5;166m                __[1;37m     [1;33m                      __                __
[1;37m#[38;5;166m     ________  / /[1;37m     [1;33m____ ___  ____ ______/ /_  ____  ____  / /__
[1;37m#[38;5;166m    / ___/ _ \/ /[1;37m_____[1;33m/ __ `__ \/ __ `/ ___/ __ \/ __ \/ __ \/ //_/
[1;37m#[38;5;166m   (__  )  __/ /[1;37m_____[1;33m/ / / / / / /_/ / /__/ /_/ / /_/ / /_/ / ,<
[1;37m#[38;5;166m  /____/\___/_/[1;37m     [1;33m/_/ /_/ /_/\__,_/\___/_.___/\____/\____/_/|_|
[1;37m#
EOF
